version: '3'

services:
  dns_exporter:
    build: .
    ports:
      - "9369:9369"
    volumes:
      - ./domains.txt:/etc/dns_exporter/domains.txt
    environment:
      - LISTEN_PORT=9369
      - CHECK_INTERVAL=60
    restart: always
