apiVersion: batch/v1
kind: Job
metadata:
  name: istio-install
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: default
      containers:
      - name: installer
        image: curlimages/curl:8.7.1              # ← образ «для проверки сети»
        command: ["/bin/sh","-c","/scripts/install-istio.sh"]
        env:
        - name: ISTIO_VERSION
          value: "{{ .Values.global.istio.version }}"
        - name: DOWNLOAD_URL
          value: "{{ .Values.global.istio.downloadUrl }}"
        volumeMounts:
        - name: scripts
          mountPath: /scripts
        - name: manifests
          mountPath: /manifests
      volumes:
      - name: scripts
        configMap:
          name: istio-installer-scripts
          defaultMode: 0755
      - name: manifests
        configMap:
          name: istio-installer-manifests
