apiVersion: batch/v1
kind: Job
metadata:
  name: istio-preclean
  namespace: {{ .Release.Namespace }}
  annotations:
    # выполняется ДО install-Job’а
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-30"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
  ttlSecondsAfterFinished: 60
  template:
    spec:
      serviceAccountName: istio-installer   # тот же cluster-admin
      restartPolicy: Never
      containers:
      - name: preclean
        image: curlimages/curl:8.7.1
        command: ["/bin/sh","-c"]
        args:
          - |
            set -e
            apk add --no-cache tar
            curl -sSL "{{ .Values.global.istio.downloadUrl }}" -o istioctl.tar.gz
            tar -xzf istioctl.tar.gz
            [ -f ./istioctl ] || mv istioctl-*/bin/istioctl ./ && chmod +x istioctl
            echo "* Remove default tag (ignore errors)…"
            ./istioctl tag remove default -y || true
            echo "* Purge previous Istio (ignore errors)…"
            yes | ./istioctl x uninstall --purge || true
