apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-installer
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: istio-installer
rules:
  # истио-ctl запрашивает/создаёт/патчит namespace и кучу CRD-ресурсов
  - apiGroups: [""]
    resources: ["namespaces", "configmaps", "secrets", "serviceaccounts", "services"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: ["install.istio.io"]
    resources: ["istiooperators"]
    verbs: ["*"]
  - apiGroups: ["networking.istio.io"]
    resources: ["gateways", "virtualservices", "destinationrules"]
    verbs: ["*"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["clusterroles", "clusterrolebindings", "roles", "rolebindings"]
    verbs: ["get", "list", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: istio-installer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: istio-installer
subjects:
  - kind: ServiceAccount
    name: istio-installer
    namespace: {{ .Release.Namespace }}
