apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-installer
  namespace: {{ .Release.Namespace }}

---
# Вместо ручного перечисления ВСЕХ verbs/resources
# привязываем сервис-аккаунт к cluster-admin.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: istio-installer-cluster-admin
  annotations:
    # hook чтобы удалялся при helm uninstall
    "helm.sh/hook": pre-install,pre-upgrade,pre-delete
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: istio-installer
    namespace: {{ .Release.Namespace }}
