apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-installer
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: istio-installer-ca
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-delete
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin          # ← максимум прав ТОЛЬКО на время хуков
subjects:
  - kind: ServiceAccount
    name: istio-installer
    namespace: {{ .Release.Namespace }}
