{{- if .Values.policy.runAsNonRoot.enabled }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-run-as-nonroot 
  labels:
    app.kubernetes.io/name: kyverno-policies
spec:
  validationFailureAction: {{ .Values.policy.runAsNonRoot.validationFailureAction | quote }}
  background: {{ .Values.policy.runAsNonRoot.background }}
  rules:
    - name: run-as-non-root
      match:
        any:
        - resources:
            kinds: ["Pod"]
      {{- if or .Values.policy.runAsNonRoot.excludeNamespaces .Values.policy.runAsNonRoot.excludeByLabel }}
      exclude:
        any:
        {{- range $ns := .Values.policy.runAsNonRoot.excludeNamespaces }}
        - resources:
            namespaces: ["{{ $ns }}"]
        {{- end }}
        {{- range $ex := .Values.policy.runAsNonRoot.excludeByLabel }}
        - resources:
            namespaces: ["{{ $ex.namespace }}"]
            selector:
              matchLabels:
              {{- range $k, $v := $ex.matchLabels }}
                {{ $k }}: {{ $v | quote }}
              {{- end }}
        {{- end }}
      {{- end }}
      validate:
        message: >-
          Running as root is not allowed. Either set spec.securityContext.runAsNonRoot=true
          or per-container securityContext.runAsNonRoot=true.
        anyPattern:
        - spec:
            securityContext:
              runAsNonRoot: true
            =(ephemeralContainers):
            - =(securityContext):
                =(runAsNonRoot): true
            =(initContainers):
            - =(securityContext):
                =(runAsNonRoot): true
            containers:
            - =(securityContext):
                =(runAsNonRoot): true
        - spec:
            =(ephemeralContainers):
            - securityContext:
                runAsNonRoot: true
            =(initContainers):
            - securityContext:
                runAsNonRoot: true
            containers:
            - securityContext:
                runAsNonRoot: true
{{- end }}
